### ISSUE TITLE
Installing SFA to jdeveloper

### ISSUE THREAD

**Issue by singr089** [HyzamAli/Sales-Force-Automation---Oracle-ADF#118] opened 2021-03-02 16:09 UTC
Hi HyzamAli, 
I am trying to run this application in my Jdev but its giving error related to database. 

Can you share the db scripts to create the tables. 

Or is there any other way I can run your application on my local machine. I want to undersatnd how it actually works. I am completly new to Oracle ADF and trying to understand the complte work flow.

**Comment by HyzamAli** [comment] 2021-03-02 16:33
Hi,
Planing to add the full setup guide in README, please star the repository to get notified.


Closing as not a bug.

**Comment by singr089** [comment] 2021-03-02 16:39
Hi HyzamAli, 
Thank you so much for the response. Can you please write it down as I have started following you. 

Also if you could write it down soon then that would be really great..

**Closed as completed** 2021-03-03 04:19 UTC
